---

- name: Set HAProxy stats user
  ansible.builtin.set_fact:
    haproxy_stats_user: "{{ lookup('env', 'HAPROXY_STATS_USER') }}"
    haproxy_stats_pass: "{{ lookup('env', 'HAPROXY_STATS_PASS') }}"
    ssl_certificate_file: "{{ lookup('env', 'SSL_CERTIFICATE_FILE') }}"
    backend_src: "{{ lookup('env', 'BACKEND_SRC') }}"
    backend_port: "{{ lookup('env', 'BACKEND_PORT') }}"

- name: Check if config file exists
  ansible.builtin.stat:
    path: /etc/haproxy/haproxy.cfg
  register: haproxy_config_file

- name: Backup config file
  become: true
  ansible.builtin.copy:
    src: /etc/haproxy/haproxy.cfg
    dest: "/home/{{ ansible_ssh_user }}/haproyx.cfg"
    remote_src: true
    mode: '0644'
  when: haproxy_config_file.stat.exists

- name: Generate config
  ansible.builtin.include_tasks:
    file: generate.yaml

- name: Restart HAProxy
  become: true
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true
